server:
  port: 9090

spring:
  application:
    name: spring-cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

    servicecomb:
      discovery:
        appName: porter-application
        serviceName: ${spring.application.name}
        enabled: true
        address: http://127.0.0.1:30100
        version: 0.0.1
        healthCheckInterval: 30