
server:
  port: 18080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
      config:
        server-addr: http://127.0.0.1:8848

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000