## Spring Boot configurations
server:
  port: 9091

spring:
  application:
    name: porter-website
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: http://127.0.0.1:30100
        appName: porter-application
        serviceName: ${spring.application.name}
        version: 0.0.1
        healthCheckInterval: 30
# need when running in huaweicloud
#      credentials:
#        enabled: true
#        accessKey: your ak
#        secretKey: your sk
#        akskCustomCipher: default
#        project: cn-east-2

