server:
  port: 8092

#servicecomb:
#  routeRule:
#    canary-provider: |
#      - precedence: 1 #优先级
#        route: #路由规则
#          - weight: 80
#            tags:
#              version: 0.0.1
#          - weight: 20
#            tags:
#              version: 0.0.2